### ISSUE TITLE
[BUG] Cannot configure DLP settings

### ISSUE THREAD

**Issue by mksmo** [linuxserver/docker-wireshark#22]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Does not applies changes in /etc/kasmvnc/kasmvnc.yaml

### Expected Behavior

I need to configure /etc/kasmvnc/kasmvnc.yaml with 
```
data_loss_prevention:
    concealed_region:
      allow_click_down: false
      allow_click_release: false
  clipboard:
    delay_between_operations: none
    allow_mimetypes:
      - chromium/x-web-custom-data
      - text/html
      - image/png
    server_to_client:
      enabled: false
      size: 1
      primary_clipboard_enabled: false
    client_to_server:
      enabled: false
      size: 1
```
Same problem with /usr/share/kasmvnc/kasmvnc_defaults.yaml

but clipboard is still available

### Steps To Reproduce

```
docker exec -it <container_name> bash
```

```
tee -a /etc/kasmvnc/kasmvnc.yaml > /dev/null <<EOL
data_loss_prevention:
  concealed_region:
    allow_click_down: false
    allow_click_release: false
clipboard:
  delay_between_operations: none
  allow_mimetypes:
    - chromium/x-web-custom-data
    - text/html
    - image/png
  server_to_client:
    enabled: false
    size: 1
    primary_clipboard_enabled: false
  client_to_server:
    enabled: false
    size: 1
EOL
```

```
exit
```

```
docker restart <container_name>
```

### Environment

```markdown
- OS:Debian Bullseye
- How docker service was installed: packagemanager
```

### CPU architecture

x86-64

### Docker creation

```bash
#docker-compose.yml
version: "2.1"
services:
  wireshark:
    image: wireshark_kasmvnc
    container_name: wireshark_kasmvnc
#    cap_add:
#      - NET_ADMIN
    security_opt:
      - seccomp:unconfined
#    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - KASM_NOCLIPBOARD=true
      - DISABLE_CLIPBOARD_INTEGRATION=true
      - DISABLE_DOWNLOAD=true
      - DISABLE_UPLOAD=true
    volumes:
      - /home/max/manual_wireshark/task1:/config
    ports:
      - 3000:3000
      - 3001:3001
    restart: unless-stopped
```

### Container logs

```bash
docker logs -f wireshark_kasmvnc 
[migrations] started
[migrations] no migrations found
───────────────────────────────────────
  _____ __ __ _____ _____ _____ _____ 
 |     |  |  |   __|_   _|     |     |
 |   --|  |  |__   | | | |  |  | | | |
 |_____|_____|_____| |_| |_____|_|_|_|
       _____ __ __ _ __    ____  
      | __  |  |  | |  |  |    \ 
      | __ -|  |  | |  |__|  |  |
      |_____|_____|_|_____|____/ 

  Based on images from linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────
[custom-init] No custom files found, skipping...

Xvnc KasmVNC 1.3.3 - built Nov 20 2024 19:38:25
Copyright (C) 1999-2018 KasmVNC Team and many others (see README.me)
See http://kasmweb.com for information on KasmVNC.
Underlying X server release 12014000, The X.Org Foundation

[ls.io-init] done.
Obt-Message: Xinerama extension is not present on the server
19
 2024-12-03 14:25:12,309 [INFO] websocket 0: got client connection from 127.0.0.1
 2024-12-03 14:25:12,317 [PRIO] Connections: accepted: @192.168.1.145_1733235912.309256::websocket
```
